// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igasufvuzlxoucpvaqsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnYXN1ZnZ1emx4b3VjcHZhcXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NjAyODcsImV4cCI6MjA1OTAzNjI4N30.2UmRt_m4LZz16KV7G_OZON7JOMQOe3tohbowxZKCrOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);